spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/taskflowdb
    username: mdakhlakurrahman
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    data:
      redis:
        host: localhost
        port: 6379

app:
  pagination:
    default-page-size: 20
    max-page-size: 100
    sort-by: id

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"